name: @name@
main: com.github.kory33.itemstackcountinfrastructure.bukkit.ItemStackCountPlugin
version: @version@

api-version: 1.17

commands:
  iscount:
    description: Command to manipulate ISCount system.
    permission: iscount.command
    permission-message: Permission denied.
    usage: "/iscount (drop-records [world_names...])|recount-all-loaded-tile-entities"

permissions:
  iscount.command:
    default: op
